# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('store', '0002_cart_cartitem')]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')],
                default='PROCESSING',
                max_length=20,
            ),
        ),
    ]
