import { useCart } from '../context/CartContext';
import { Link } from 'react-router-dom';
import { formatPrice, productImage } from '../utils/store';

export default function CartPage() {
  const { cartItems, total, loading, removeFromCart, updateQuantity } = useCart();
  if (loading) return <main className='grid min-h-[70vh] place-items-center text-slate-500'>Loading your cart…</main>;
  return <main className='min-h-screen bg-slate-50 px-4 py-10 md:px-8'><section className='mx-auto max-w-6xl'><p className='text-sm font-bold uppercase tracking-[.18em] text-violet-600'>Your bag</p><h1 className='mt-2 text-3xl font-black text-slate-900'>Shopping cart</h1>
    {cartItems.length === 0 ? <div className='mt-8 rounded-3xl bg-white px-6 py-16 text-center shadow-sm'><div className='text-4xl'>◌</div><h2 className='mt-4 text-xl font-bold'>Your cart is empty</h2><p className='mt-2 text-slate-500'>Save your favorites here when you are ready.</p><Link to='/' className='mt-6 inline-block rounded-full bg-violet-600 px-5 py-3 font-bold text-white'>Explore products</Link></div> : <div className='mt-8 grid gap-7 lg:grid-cols-[1fr_340px]'><div className='overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-100'>{cartItems.map(item => <div key={item.id} className='flex gap-4 border-b border-slate-100 p-4 last:border-0 sm:p-6'>{item.product_image ? <img src={productImage(item.product_image)} alt={item.product_name} className='h-20 w-20 rounded-2xl bg-slate-100 object-contain p-1 sm:h-24 sm:w-24' /> : <div className='grid h-20 w-20 place-items-center rounded-2xl bg-slate-100 text-slate-300'>✦</div>}<div className='min-w-0 flex-1'><div className='flex justify-between gap-3'><div><h2 className='truncate font-bold text-slate-900'>{item.product_name}</h2><p className='mt-1 font-semibold text-violet-700'>{formatPrice(item.product_price)}</p></div><button onClick={() => removeFromCart(item.id)} className='text-sm font-semibold text-rose-500 hover:text-rose-700'>Remove</button></div><div className='mt-4 flex items-center gap-3'><div className='flex items-center rounded-full border border-slate-200'><button aria-label='Decrease quantity' onClick={() => updateQuantity(item.id, item.quantity - 1)} className='px-3 py-1 text-lg'>−</button><span className='min-w-8 text-center text-sm font-bold'>{item.quantity}</span><button aria-label='Increase quantity' onClick={() => updateQuantity(item.id, item.quantity + 1)} className='px-3 py-1 text-lg'>+</button></div><span className='text-sm text-slate-500'>Subtotal: {formatPrice(Number(item.product_price) * item.quantity)}</span></div></div></div>)}</div><aside className='h-fit rounded-3xl bg-slate-900 p-6 text-white'><h2 className='text-xl font-black'>Order summary</h2><div className='mt-6 flex justify-between text-slate-300'><span>Subtotal</span><span>{formatPrice(total)}</span></div><div className='mt-3 flex justify-between text-slate-300'><span>Delivery</span><span>Calculated at checkout</span></div><div className='mt-6 flex justify-between border-t border-slate-700 pt-5 text-lg font-black'><span>Total</span><span>{formatPrice(total)}</span></div><Link to='/checkout' className='mt-6 block rounded-full bg-violet-500 px-5 py-3 text-center font-bold transition hover:bg-violet-400'>Continue to checkout</Link><Link to='/' className='mt-4 block text-center text-sm font-semibold text-slate-300 hover:text-white'>Continue shopping</Link></aside></div>}</section></main>;
}
